export const services = [
  {
    service: "CUSTOM SIGNS MAKERS",
    slug: "custom-signs-makers",
    subservices: [
      {
        name: "Channel Letter",
        image_url: "/imagesservices/CUSTOMSIGNSMAKERS/CHANNELLETTER/bla.jpg",
        description: "",
        benefits: [
          "24/7 Visibility: Bright LED illumination ensures your sign is visible day and night, increasing brand exposure around the clock.",
          "Energy Efficient: Modern LED technology provides brilliant lighting with minimal power consumption and long-lasting performance.",
          "Custom Design: Choose from various fonts, colors, sizes, and finishes to perfectly match your brand identity.",
          "Weather Resistant: Built to withstand harsh outdoor conditions, maintaining appearance and functionality for years.",
        ],
        gallery: [
          "/imagesservices/CUSTOMSIGNSMAKERS/CHANNELLETTER/bla.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/CHANNELLETTER/ImagendeWhatsApp2025-11-30alas08.51.34_2a7e8054.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/CHANNELLETTER/ImagendeWhatsApp2025-11-30alas09.04.12_ed1f753c.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/CHANNELLETTER/ImagendeWhatsApp2025-11-30alas09.04.29_97f6f9a4.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/CHANNELLETTER/ImagendeWhatsApp2025-11-30alas09.12.58_aed74613.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/CHANNELLETTER/ImagendeWhatsApp2025-12-07alas19.29.04_eadb6054.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/CHANNELLETTER/ImagendeWhatsApp2025-12-07alas19.30.38_6c273f1d.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/CHANNELLETTER/ImagendeWhatsApp2025-12-07alas19.36.54_d9483ea3.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/CHANNELLETTER/ImagendeWhatsApp2025-12-07alas19.38.13_79834601.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/CHANNELLETTER/ImagendeWhatsApp2025-12-07alas19.41.26_0ad102a0.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/CHANNELLETTER/IMG-20250819-WA0006.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/CHANNELLETTER/IMG-20250905-WA0012.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/CHANNELLETTER/IMG-20251109-WA0010.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/CHANNELLETTER/IMG-20251109-WA0014.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/CHANNELLETTER/IMG-20251109-WA0017.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/CHANNELLETTER/IMG-20251109-WA0019.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/CHANNELLETTER/IMG-20251109-WA0032.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/CHANNELLETTER/IMG-20251115-WA0002.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/CHANNELLETTER/IMG-20251201-WA0047.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/CHANNELLETTER/IMG-20251201-WA0108.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/CHANNELLETTER/CHANNEL.jpg",

        ],
      },
      {
        name: "Lightboxes",
        image_url: "/imagesservices/CUSTOMSIGNSMAKERS/LIGHTBOXES/1.jpg",
        description: "",
        benefits: [
          "High-Impact Display: Backlit graphics appear more vibrant and eye-catching than traditional signs, attracting more attention.",
          "Easy Graphic Updates: Swap out graphics quickly and easily to update promotions, messages, or seasonal campaigns.",
          "Versatile Applications: Suitable for both indoor and outdoor use in various sizes and configurations.",
          "Energy Efficient Lighting: Modern LED systems provide bright, even illumination with low power consumption.",
        ],
        gallery: [
          "/imagesservices/CUSTOMSIGNSMAKERS/LIGHTBOXES/1.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/LIGHTBOXES/2.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/LIGHTBOXES/3.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/LIGHTBOXES/4.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/LIGHTBOXES/5.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/LIGHTBOXES/6.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/LIGHTBOXES/7.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/LIGHTBOXES/8.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/LIGHTBOXES/9.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/LIGHTBOXES/10.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/LIGHTBOXES/11.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/LIGHTBOXES/12.jpg",

        ],
      },
      {
        name: "Neon Signs",
        image_url: "/imagesservices/CUSTOMSIGNSMAKERS/NEONSIGNS/neon1.jpg",
        description: "",
        benefits: [
          "Retro Aesthetic: Classic neon look creates a unique and memorable brand identity that stands out from competitors.",
          "Custom Designs: Bend into virtually any shape, letter, or logo with a wide range of color options available.",
          "Long-Lasting: Modern neon alternatives offer longer lifespan and easier maintenance than traditional glass neon.",
          "Atmospheric Lighting: Creates ambiance and mood in addition to providing effective signage.",
        ],
        gallery: [
          "/imagesservices/CUSTOMSIGNSMAKERS/NEONSIGNS/neon1.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/NEONSIGNS/neon2.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/NEONSIGNS/neon3.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/NEONSIGNS/neon4.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/NEONSIGNS/neon5.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/NEONSIGNS/neon6.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/NEONSIGNS/neon7.jpg",

        ],
      },
      {
        name: "Non-Illuminated Signs",
        image_url:
          "/imagesservices/CUSTOMSIGNSMAKERS/NONILLUMINATEDSIGNS/1.jpg",
        description: "",
        benefits: [
          "Budget-Friendly: High-quality signage at a lower cost than illuminated options, perfect for daytime businesses.",
          "Versatile Materials: Choose from acrylic, metal, wood, PVC, or vinyl to match your aesthetic and budget.",
          "Quick Production: Faster turnaround times compared to illuminated signs for urgent needs.",
          "Easy Installation: Lightweight designs that are simple to mount in various locations and surfaces.",
        ],
        gallery: [
          "/imagesservices/CUSTOMSIGNSMAKERS/NONILLUMINATEDSIGNS/1.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/NONILLUMINATEDSIGNS/2.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/NONILLUMINATEDSIGNS/3.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/NONILLUMINATEDSIGNS/4.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/NONILLUMINATEDSIGNS/5.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/NONILLUMINATEDSIGNS/6.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/NONILLUMINATEDSIGNS/7.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/NONILLUMINATEDSIGNS/8.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/NONILLUMINATEDSIGNS/9.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/NONILLUMINATEDSIGNS/10.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/NONILLUMINATEDSIGNS/11.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/NONILLUMINATEDSIGNS/12.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/NONILLUMINATEDSIGNS/13.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/NONILLUMINATEDSIGNS/14.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/NONILLUMINATEDSIGNS/15.jpg",

        ],
      },
      {
        name: "Indoor Signs",
        image_url: "/imagesservices/CUSTOMSIGNSMAKERS/INDOORSIGNS/1.jpg",
        description: "",
        benefits: [
          "Improved Navigation: Clear wayfinding signs help visitors easily find their way around your facility.",
          "Professional Environment: High-quality interior signage creates a polished, professional atmosphere.",
          "Brand Reinforcement: Consistent interior branding strengthens brand identity throughout your space.",
          "Custom Sizing: Signs tailored to fit perfectly in your specific indoor locations and spaces.",
        ],
        gallery: [
          "/imagesservices/CUSTOMSIGNSMAKERS/INDOORSIGNS/1.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/INDOORSIGNS/2.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/INDOORSIGNS/3.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/INDOORSIGNS/ImagendeWhatsApp2025-11-30alas09.03.02_17305e8b.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/INDOORSIGNS/ImagendeWhatsApp2025-11-30alas09.33.21_4c18bc8d.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/INDOORSIGNS/ImagendeWhatsApp2025-11-30alas09.33.38_2f1ffe1e.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/INDOORSIGNS/ImagendeWhatsApp2025-11-30alas09.35.39_d930be10.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/INDOORSIGNS/ImagendeWhatsApp2025-11-30alas.09.36.15_081c7774.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/INDOORSIGNS/ImagendeWhatsApp2025-12-07alas19.01.07_080a05c5.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/INDOORSIGNS/ImagendeWhatsApp2025-12-07alas19.01.08_50366ed0.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/INDOORSIGNS/ImagendeWhatsApp2025-12-07alas19.01.19_4f34533c.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/INDOORSIGNS/ImagendeWhatsApp2025-12-07alas19.04.37_90f94ec7.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/INDOORSIGNS/ImagendeWhatsApp2025-12-07alas19.31.15_31064b83.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/INDOORSIGNS/ImagendeWhatsApp2025-12-07alas19.31.16_82dbd1ea.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/INDOORSIGNS/IMG-20250819-WA0004.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/INDOORSIGNS/IMG-20251201-WA0077.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/INDOORSIGNS/IMG-20251201-WA0079.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/INDOORSIGNS/IMG-20251201-WA0085.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/INDOORSIGNS/IMG-20251201-WA0103.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/INDOORSIGNS/IMG-20251209-WA0065.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/INDOORSIGNS/IMG-20251209-WA0067.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/INDOORSIGNS/IMG-20251209-WA0069.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/INDOORSIGNS/IndoorSigns1.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/INDOORSIGNS/IndoorSigns2.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/INDOORSIGNS/VID-20251209-WA0001.jpg",
          "/imagesservices/CUSTOMSIGNSMAKERS/INDOORSIGNS/VID-20251209-WA0002.jpg",
        ],
      },
    ],
  },
  {
    service: "CAR WRAP",
    slug: "car-wrap",
    subservices: [
      {
        name: "Partial Car Wrap",
        image_url: "/imagesservices/CARWRAP/PARTIALCARWRAP/1.jpg",
        description: "",
        benefits: [
          "Cost-Effective Solution: Achieve significant visual impact at a lower investment than full wraps.",
          "Targeted Advertising: Focus graphics on the most visible areas of your vehicle for maximum exposure.",
          "Faster Installation: Reduced coverage area means quicker turnaround and less downtime for your vehicle.",
          "Design Flexibility: Combine wrapped sections with your vehicle's original color for unique visual effects.",
        ],
        gallery: [
          "/imagesservices/CARWRAP/PARTIALCARWRAP/1.jpg",
          "/imagesservices/CARWRAP/PARTIALCARWRAP/2.jpg",
          "/imagesservices/CARWRAP/PARTIALCARWRAP/3.jpg",
          "/imagesservices/CARWRAP/PARTIALCARWRAP/4.jpg",
          "/imagesservices/CARWRAP/PARTIALCARWRAP/5.jpg",
          "/imagesservices/CARWRAP/PARTIALCARWRAP/6.jpg",
          "/imagesservices/CARWRAP/PARTIALCARWRAP/7.jpg",
          "/imagesservices/CARWRAP/PARTIALCARWRAP/8.jpg",
          "/imagesservices/CARWRAP/PARTIALCARWRAP/9.jpg",
          "/imagesservices/CARWRAP/PARTIALCARWRAP/10.jpg",
          "/imagesservices/CARWRAP/PARTIALCARWRAP/11.jpg",
          "/imagesservices/CARWRAP/PARTIALCARWRAP/12.jpg",
          "/imagesservices/CARWRAP/PARTIALCARWRAP/13.jpg",
          "/imagesservices/CARWRAP/PARTIALCARWRAP/14.jpg",
          "/imagesservices/CARWRAP/PARTIALCARWRAP/15.jpg",
          "/imagesservices/CARWRAP/PARTIALCARWRAP/16.jpg",
          "/imagesservices/CARWRAP/PARTIALCARWRAP/17.jpg",
          "/imagesservices/CARWRAP/PARTIALCARWRAP/18.jpg",
          "/imagesservices/CARWRAP/PARTIALCARWRAP/19.jpg",
          "/imagesservices/CARWRAP/PARTIALCARWRAP/20.jpg",
          "/imagesservices/CARWRAP/PARTIALCARWRAP/21.jpg",
          "/imagesservices/CARWRAP/PARTIALCARWRAP/22.jpg",
          "/imagesservices/CARWRAP/PARTIALCARWRAP/23.jpg",
          "/imagesservices/CARWRAP/PARTIALCARWRAP/24.jpg",
          "/imagesservices/CARWRAP/PARTIALCARWRAP/25.jpg",
          "/imagesservices/CARWRAP/PARTIALCARWRAP/26.jpg",
          "/imagesservices/CARWRAP/PARTIALCARWRAP/27.jpg",
          "/imagesservices/CARWRAP/PARTIALCARWRAP/28.jpg",
          "/imagesservices/CARWRAP/PARTIALCARWRAP/29.jpg",
          "/imagesservices/CARWRAP/PARTIALCARWRAP/30.jpg",
          "/imagesservices/CARWRAP/PARTIALCARWRAP/31.jpg",
          "/imagesservices/CARWRAP/PARTIALCARWRAP/32.jpg",

        ],
      },
      {
        name: "Full Car Wrap",
        image_url: "/imagesservices/CARWRAP/FULLCARWRAP/1.jpg",
        description: "",
        benefits: [
          "Maximum Advertising Space: 100% coverage creates a stunning, attention-grabbing mobile billboard.",
          "Complete Paint Protection: Full shield against UV rays, minor scratches, road debris, and environmental damage.",
          "Total Design Freedom: Create intricate, seamless designs that flow across the entire vehicle surface.",
          "Resale Value Protection: Remove the wrap to reveal pristine original paint when selling your vehicle.",
        ],
        gallery: [
          "/imagesservices/CARWRAP/FULLCARWRAP/1.jpg",
          "/imagesservices/CARWRAP/FULLCARWRAP/2.jpg",
          "/imagesservices/CARWRAP/FULLCARWRAP/3.jpg",
          "/imagesservices/CARWRAP/FULLCARWRAP/4.jpg",
          "/imagesservices/CARWRAP/FULLCARWRAP/5.jpg",
          "/imagesservices/CARWRAP/FULLCARWRAP/6.jpg",
          "/imagesservices/CARWRAP/FULLCARWRAP/7.jpg",
          "/imagesservices/CARWRAP/FULLCARWRAP/8.jpg",
          "/imagesservices/CARWRAP/FULLCARWRAP/9.jpg",
          "/imagesservices/CARWRAP/FULLCARWRAP/10.jpg",
          "/imagesservices/CARWRAP/FULLCARWRAP/11.jpg",
          "/imagesservices/CARWRAP/FULLCARWRAP/12.jpg",
          "/imagesservices/CARWRAP/FULLCARWRAP/13.jpg",
          "/imagesservices/CARWRAP/FULLCARWRAP/14.jpg",
          "/imagesservices/CARWRAP/FULLCARWRAP/15.jpg",
          "/imagesservices/CARWRAP/FULLCARWRAP/16.jpg",
        ],
      },
    ],
  },
  {
    service: "PROMOTIONAL PRODUCTS",
    slug: "promotional-products",
    subservices: [
      {
        name: "T-Shirts",
        image_url: "/imagesservices/PROMOTIONALPRODUCTS/T-SHIRTS/1.jpg",
        description: "",
        benefits: [
          "Mobile Advertising: Every wearer becomes a moving advertisement for your brand, reaching new audiences daily.",
          "Team Unity: Create matching shirts for employees to build team spirit and present a unified professional image.",
          "Event Merchandise: Perfect for concerts, conferences, sports events, and special occasions.",
          "High-Quality Prints: Durable printing that withstands repeated washing without fading or cracking.",
        ],
        gallery: [
          "/imagesservices/PROMOTIONALPRODUCTS/T-SHIRTS/1.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/T-SHIRTS/2.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/T-SHIRTS/3.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/T-SHIRTS/4.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/T-SHIRTS/5.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/T-SHIRTS/6.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/T-SHIRTS/7.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/T-SHIRTS/8.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/T-SHIRTS/9.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/T-SHIRTS/10.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/T-SHIRTS/11.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/T-SHIRTS/12.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/T-SHIRTS/13.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/T-SHIRTS/14.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/T-SHIRTS/15.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/T-SHIRTS/16.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/T-SHIRTS/17.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/T-SHIRTS/18.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/T-SHIRTS/19.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/T-SHIRTS/20.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/T-SHIRTS/21.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/T-SHIRTS/22.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/T-SHIRTS/23.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/T-SHIRTS/24.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/T-SHIRTS/25.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/T-SHIRTS/26.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/T-SHIRTS/27.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/T-SHIRTS/28.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/T-SHIRTS/29.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/T-SHIRTS/30.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/T-SHIRTS/31.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/T-SHIRTS/32.jpg",

        ],
      },
      {
        name: "Caps",
        image_url: "/imagesservices/PROMOTIONALPRODUCTS/CAPS/1.jpg",
        description: "",
        benefits: [
          "Head-Turning Branding: Caps place your logo at eye level, ensuring maximum visibility in crowds.",
          "Practical Promotion: Useful items that people actually want to wear, ensuring repeated brand exposure.",
          "Versatile Styles: Available in various styles including baseball caps, snapbacks, beanies, and bucket hats.",
          "Quality Construction: Durable materials and precise embroidery for long-lasting brand representation.",
        ],
        gallery: [
          "/imagesservices/PROMOTIONALPRODUCTS/CAPS/1.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/CAPS/2.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/CAPS/3.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/CAPS/4.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/CAPS/5.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/CAPS/6.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/CAPS/7.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/CAPS/8.jpg",
        ],
      },
      {
        name: "Key Chain",
        image_url: "/imagesservices/PROMOTIONALPRODUCTS/KEYCHAIN/1.jpg",
        description: "",
        benefits: [
          "Daily Exposure: Keychains are used multiple times daily, offering consistent brand visibility.",
          "High Retention Rate: Practical items that people keep for years, providing long-term advertising.",
          "Cost-Effective: Affordable production costs with exceptional return on investment potential.",
          "Perfect Giveaways: Ideal for trade shows, corporate gifts, customer appreciation, and event souvenirs.",
        ],
        gallery: [
          "/imagesservices/PROMOTIONALPRODUCTS/KEYCHAIN/1.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/KEYCHAIN/2.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/KEYCHAIN/3.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/KEYCHAIN/4.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/KEYCHAIN/5.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/KEYCHAIN/6.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/KEYCHAIN/7.jpg",

        ],
      },
      {
        name: "Roll-Up",
        image_url: "/imagesservices/PROMOTIONALPRODUCTS/ROLL-UP/1.jpg",
        description: "",
        benefits: [
          "Quick Setup: Unfolds and sets up in minutes, perfect for busy events and last-minute presentations.",
          "Professional Appearance: Crisp graphics on taut fabric create a polished, professional display.",
          "Portable Design: Lightweight and compact when rolled up, easy to transport between locations.",
          "Reusable: Durable construction allows for repeated use at multiple events over years.",
        ],
        gallery: [
          "/imagesservices/PROMOTIONALPRODUCTS/ROLL-UP/1.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/ROLL-UP/2.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/ROLL-UP/3.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/ROLL-UP/4.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/ROLL-UP/5.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/ROLL-UP/6.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/ROLL-UP/7.jpg",

        ],
      },
      {
        name: "Car Magnet",
        image_url: "/imagesservices/PROMOTIONALPRODUCTS/CARMAGNET/1.jpg",
        description: "",
        benefits: [
          "Easy Application: Simply place on clean vehicle surface - no tools or installation required.",
          "Removable & Reusable: Remove when not needed, reapply multiple times without damage to vehicle.",
          "Cost-Effective Advertising: Turn personal vehicles into mobile ads without permanent commitment.",
          "Multiple Vehicle Use: One magnet can be moved between different vehicles as needed.",
        ],
        gallery: [
          "/imagesservices/PROMOTIONALPRODUCTS/CARMAGNET/1.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/CARMAGNET/2.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/CARMAGNET/3.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/CARMAGNET/4.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/CARMAGNET/5.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/CARMAGNET/6.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/CARMAGNET/7.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/CARMAGNET/8.jpg",
        ],
      },
      {
        name: "A-Frame",
        image_url: "/imagesservices/PROMOTIONALPRODUCTS/A-FRAME/1.jpg",
        description: "",
        benefits: [
          "Foot Traffic Attention: Positioned at street level to catch the eye of pedestrians and passing drivers.",
          "Daily Updates: Easily change messages to promote daily specials, events, or seasonal offers.",
          "Weather Resistant: Designed for outdoor use with materials that withstand various weather conditions.",
          "Portable Placement: Light enough to move to optimal locations, heavy enough to stay in place.",
        ],
        gallery: [
          "/imagesservices/PROMOTIONALPRODUCTS/A-FRAME/1.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/A-FRAME/2.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/A-FRAME/3.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/A-FRAME/4.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/A-FRAME/5.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/A-FRAME/6.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/A-FRAME/7.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/A-FRAME/8.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/A-FRAME/9.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/A-FRAME/10.jpg",
        ],
      },
      {
        name: "Flags",
        image_url: "/imagesservices/PROMOTIONALPRODUCTS/FLAGS/1.jpg",
        description: "",
        benefits: [
          "High Visibility: Moving flags naturally draw the eye, making them highly effective for attention capture.",
          "Location Marking: Clearly identify your business location from a distance to guide customers.",
          "Event Promotion: Perfect for grand openings, sales events, festivals, and special promotions.",
          "Durable Materials: Weather-resistant fabrics and printing for long-lasting outdoor use.",
        ],
        gallery: [
          "/imagesservices/PROMOTIONALPRODUCTS/FLAGS/1.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/FLAGS/2.jpg",
          "/imagesservices/PROMOTIONALPRODUCTS/FLAGS/3.jpg",

        ],
      },
    ],
  },
  {
    service: "MARKETING MATERIALS",
    slug: "marketing-materials",
    subservices: [
      {
        name: "Business Cards",
        image_url: "/imagesservices/MARKETINGMATERIALS/BUSINESSCARDS/1.jpg",
        description: "",
        benefits: [
          "Professional Introduction: High-quality cards establish immediate credibility and trust with new contacts.",
          "Brand Consistency: Cards that perfectly match your company's visual identity and messaging.",
          "Networking Essential: The most effective and professional way to exchange contact information.",
          "Creative Options: Various paper stocks, finishes, special cuts, and printing effects available.",
        ],
        gallery: [
          "/imagesservices/MARKETINGMATERIALS/BUSINESSCARDS/1.jpg",
          "/imagesservices/MARKETINGMATERIALS/BUSINESSCARDS/2.jpg",
          "/imagesservices/MARKETINGMATERIALS/BUSINESSCARDS/3.jpg",
          "/imagesservices/MARKETINGMATERIALS/BUSINESSCARDS/4.jpg",
          "/imagesservices/MARKETINGMATERIALS/BUSINESSCARDS/5.jpg",
          "/imagesservices/MARKETINGMATERIALS/BUSINESSCARDS/6.jpg",
          "/imagesservices/MARKETINGMATERIALS/BUSINESSCARDS/7.jpg",
          "/imagesservices/MARKETINGMATERIALS/BUSINESSCARDS/8.jpg",
          "/imagesservices/MARKETINGMATERIALS/BUSINESSCARDS/9.jpg",
        ],
      },
      {
        name: "Postcards",
        image_url: "/imagesservices/MARKETINGMATERIALS/POSTCARDS/1.jpg",
        description: "",
        benefits: [
          "Direct Engagement: Physical mail that customers hold and examine, creating stronger engagement than digital.",
          "Versatile Use: Announce openings, promote sales, share news, or simply stay top-of-mind with customers.",
          "Cost-Effective Mailing: Standard postcard postage rates are lower than letter mail, saving on campaign costs.",
          "High Impact Design: One side for eye-catching imagery, the other for compelling message and call-to-action.",
        ],
        gallery: [
          "/imagesservices/MARKETINGMATERIALS/POSTCARDS/1.jpg",
          "/imagesservices/MARKETINGMATERIALS/POSTCARDS/2.jpg",
          "/imagesservices/MARKETINGMATERIALS/POSTCARDS/3.jpg",
          "/imagesservices/MARKETINGMATERIALS/POSTCARDS/4.jpg",
        ],
      },
      {
        name: "Flyers and Brochures",
        image_url:
          "/imagesservices/MARKETINGMATERIALS/FLYERSANDBROCHURES/1.jpg",
        description: "",
        benefits: [
          "Detailed Information: Space to thoroughly explain products, services, events, or special offers.",
          "Multiple Distribution Methods: Hand out at events, include in mailings, or display in-store for pickup.",
          "Professional Presentation: Well-designed brochures establish credibility and thoroughness.",
          "Folding Options: Various fold styles (bi-fold, tri-fold, z-fold) to organize information effectively.",
        ],
        gallery: [
          "/imagesservices/MARKETINGMATERIALS/FLYERSANDBROCHURES/1.jpg",
          "/imagesservices/MARKETINGMATERIALS/FLYERSANDBROCHURES/2.jpg",
          "/imagesservices/MARKETINGMATERIALS/FLYERSANDBROCHURES/3.jpg",
          "/imagesservices/MARKETINGMATERIALS/FLYERSANDBROCHURES/4.jpg",

        ],
      },
      {
        name: "Stickers",
        image_url: "/imagesservices/MARKETINGMATERIALS/STICKERS/1.jpg",
        description: "",
        benefits: [
          "Ubiquitous Branding: Place on products, packaging, laptops, vehicles, windows - virtually any surface.",
          "Customer Engagement: People love collecting and displaying interesting stickers, increasing brand interaction.",
          "Cost-Effective Production: Affordable to produce in large quantities for widespread distribution.",
          "Various Materials: Choose from paper, vinyl, holographic, transparent, or waterproof options.",
        ],
        gallery: [
          "/imagesservices/MARKETINGMATERIALS/STICKERS/1.jpg",
          "/imagesservices/MARKETINGMATERIALS/STICKERS/2.jpg",
          "/imagesservices/MARKETINGMATERIALS/STICKERS/3.jpg",
          "/imagesservices/MARKETINGMATERIALS/STICKERS/4.jpg",
          "/imagesservices/MARKETINGMATERIALS/STICKERS/5.jpg",
          "/imagesservices/MARKETINGMATERIALS/STICKERS/6.jpg",
          "/imagesservices/MARKETINGMATERIALS/STICKERS/7.jpg",
          "/imagesservices/MARKETINGMATERIALS/STICKERS/8.jpg",
          "/imagesservices/MARKETINGMATERIALS/STICKERS/9.jpg",
          "/imagesservices/MARKETINGMATERIALS/STICKERS/10.jpg",
          "/imagesservices/MARKETINGMATERIALS/STICKERS/11.jpg",

        ],
      },
      {
        name: "Invoice",
        image_url: "/imagesservices/MARKETINGMATERIALS/INVOICE/1.jpg",
        description: "",
        benefits: [
          "Brand Reinforcement: Every transaction becomes another touchpoint reinforcing your professional image.",
          "Professional Appearance: Custom-designed invoices look more credible than generic templates.",
          "Complete Branding: Include logos, colors, and consistent messaging across all customer documents.",
          "Information Organization: Clearly organized layout makes it easy for clients to understand charges and payment terms.",
        ],
        gallery: [
          "/imagesservices/MARKETINGMATERIALS/INVOICE/1.jpg",
          "/imagesservices/MARKETINGMATERIALS/INVOICE/2.jpg",
          "/imagesservices/MARKETINGMATERIALS/INVOICE/3.jpg",
          "/imagesservices/MARKETINGMATERIALS/INVOICE/4.jpg",

        ],
      },
      {
        name: "Yard Signs",
        image_url: "/imagesservices/MARKETINGMATERIALS/YARDSIGNS/1.jpg",
        description: "",
        benefits: [
          "Local Targeting: Perfect for reaching specific neighborhoods, communities, or event locations.",
          "High Visibility: Large format and strategic placement ensure messages are seen by passing traffic.",
          "Weather Durable: Corrugated plastic or other weather-resistant materials for outdoor longevity.",
          "Temporary Promotions: Ideal for time-sensitive messaging like open houses, elections, or limited-time offers.",
        ],
        gallery: [
          "/imagesservices/MARKETINGMATERIALS/YARDSIGNS/1.jpg",
          "/imagesservices/MARKETINGMATERIALS/YARDSIGNS/2.jpg",
          "/imagesservices/MARKETINGMATERIALS/YARDSIGNS/3.jpg",
          "/imagesservices/MARKETINGMATERIALS/YARDSIGNS/4.jpg",

        ],
      },
    ],
  },
  {
    service: "WIDE FORMAT PRINTS",
    slug: "wide-format-prints",
    subservices: [
      {
        name: "ACRYLIC PRINTS",
        image_url: "/imagesservices/WIDEFORMATPRINTS/ACRYLICPRINTS/1.jpg",
        description: "",
        benefits: [
          "Crystal Clear Appearance: Acrylic provides exceptional clarity and depth, making colors pop with brilliant intensity.",
          "Durable & Scratch Resistant: Withstands daily wear and tear while maintaining its pristine appearance.",
          "Modern & Professional: Sleek, contemporary look that enhances any business or residential space.",
          "Lightweight Yet Strong: Easier to install than glass while offering similar visual quality and durability.",
          "UV Resistant: Colors remain vibrant and fade-resistant even with prolonged sun exposure.",
        ],
        gallery: [
          "/imagesservices/WIDEFORMATPRINTS/ACRYLICPRINTS/1.jpg",
          "/imagesservices/WIDEFORMATPRINTS/ACRYLICPRINTS/2.jpg",
          "/imagesservices/WIDEFORMATPRINTS/ACRYLICPRINTS/3.jpg",
          "/imagesservices/WIDEFORMATPRINTS/ACRYLICPRINTS/4.jpg",
          "/imagesservices/WIDEFORMATPRINTS/ACRYLICPRINTS/5.jpg",
          "/imagesservices/WIDEFORMATPRINTS/ACRYLICPRINTS/6.jpg",
          "/imagesservices/WIDEFORMATPRINTS/ACRYLICPRINTS/7.jpg",
          "/imagesservices/WIDEFORMATPRINTS/ACRYLICPRINTS/8.jpg",
          "/imagesservices/WIDEFORMATPRINTS/ACRYLICPRINTS/9.jpg",

        ],
      },
      {
        name: "BANNERS, ALUMINUM AND COROPLAST",
        image_url: "/imagesservices/WIDEFORMATPRINTS/BANNERS/1.jpg",
        description: "",
        benefits: [
          "Highly Visible: Large format ensures maximum visibility for promotions, events, and advertising.",
          "Weather Resistant: Outdoor banners withstand sun, rain, and wind while maintaining color integrity.",
          "Versatile Applications: Perfect for trade shows, storefronts, events, construction sites, and more.",
          "Quick Turnaround: Fast production allows for timely promotions and event advertising.",
          "Cost-Effective Marketing: Provides extensive advertising reach at a fraction of traditional media costs.",
        ],
        gallery: [
          "/imagesservices/WIDEFORMATPRINTS/BANNERS/1.jpg",
          "/imagesservices/WIDEFORMATPRINTS/BANNERS/2.jpg",
          "/imagesservices/WIDEFORMATPRINTS/BANNERS/3.jpg",
          "/imagesservices/WIDEFORMATPRINTS/BANNERS/4.jpg",
          "/imagesservices/WIDEFORMATPRINTS/BANNERS/5.jpg",
          "/imagesservices/WIDEFORMATPRINTS/BANNERS/6.jpg",
          "/imagesservices/WIDEFORMATPRINTS/BANNERS/7.jpg",
          "/imagesservices/WIDEFORMATPRINTS/BANNERS/8.jpg",
          "/imagesservices/WIDEFORMATPRINTS/BANNERS/9.jpg",
          "/imagesservices/WIDEFORMATPRINTS/BANNERS/10.jpg",
          "/imagesservices/WIDEFORMATPRINTS/BANNERS/11.jpg",
          "/imagesservices/WIDEFORMATPRINTS/BANNERS/12.jpg",
          "/imagesservices/WIDEFORMATPRINTS/BANNERS/13.jpg",
          "/imagesservices/WIDEFORMATPRINTS/BANNERS/14.jpg",

        ],
      },
      {
        name: "CANVAS PRINTS",
        image_url: "/imagesservices/WIDEFORMATPRINTS/CANVASPRINTS/1.jpg",
        description: "",
        benefits: [
          "Artistic Appeal: Canvas texture adds an artistic, gallery-quality look to any image or design.",
          "Ready to Hang: Comes stretched on frames for immediate display without additional framing needs.",
          "Fade Resistant: High-quality inks ensure colors remain vibrant for years without fading.",
          "Versatile Decor: Perfect for offices, homes, restaurants, hotels, and commercial spaces.",
          "Professional Finish: Gallery-wrapped edges provide a clean, professional appearance.",
        ],
        gallery: [
          "/imagesservices/WIDEFORMATPRINTS/CANVASPRINTS/1.jpg",
          "/imagesservices/WIDEFORMATPRINTS/CANVASPRINTS/2.jpg",
          "/imagesservices/WIDEFORMATPRINTS/CANVASPRINTS/3.jpg",
          "/imagesservices/WIDEFORMATPRINTS/CANVASPRINTS/4.jpg",
        ],
      },
      {
        name: "FLOOR DECALS",
        image_url: "/imagesservices/WIDEFORMATPRINTS/FLOORDECALS/1.jpg",
        description: "",
        benefits: [
          "High Traffic Durability: Specialized materials withstand foot traffic, carts, and cleaning.",
          "Slip Resistant Surface: Safety-focused finishes prevent slips and falls in busy areas.",
          "Effective Wayfinding: Guide customers through stores, offices, and public spaces with clear directional graphics.",
          "Creative Advertising: Capture attention at eye level with promotional messages on floors.",
          "Easy Application & Removal: Professional installation with clean removal when needed.",
        ],
        gallery: [
          "/imagesservices/WIDEFORMATPRINTS/FLOORDECALS/1.jpg",
          "/imagesservices/WIDEFORMATPRINTS/FLOORDECALS/2.jpg",
        ],
      },
      {
        name: "MONUMENT AND PYLON SIGNS",
        image_url:
          "/imagesservices/WIDEFORMATPRINTS/MONUMENTANDPYLONSIGNS/1.jpg",
        description: "",
        benefits: [
          "Premium Brand Presence: Makes a strong statement about your business quality and permanence.",
          "Excellent Visibility: Tall structures ensure visibility from roads and surrounding areas.",
          "Durable Construction: Built with weather-resistant materials for long-term outdoor performance.",
          "Custom Design Options: Tailored to match architectural styles and corporate branding.",
          "Increased Property Value: Professional signage enhances curb appeal and property value.",
        ],
        gallery: [
          "/imagesservices/WIDEFORMATPRINTS/MONUMENTANDPYLONSIGNS/1.jpg",
          "/imagesservices/WIDEFORMATPRINTS/MONUMENTANDPYLONSIGNS/2.jpg",
          "/imagesservices/WIDEFORMATPRINTS/MONUMENTANDPYLONSIGNS/3.jpg",
          "/imagesservices/WIDEFORMATPRINTS/MONUMENTANDPYLONSIGNS/4.jpg",
        ],
      },
      {
        name: "PVC PRINTS",
        image_url: "/imagesservices/WIDEFORMATPRINTS/PVCPRINTS/1.jpg",
        description: "",
        benefits: [
          "Weather Resistant: Performs well in both indoor and outdoor environments.",
          "Lightweight & Rigid: Easy to handle and install while maintaining structural integrity.",
          "Cost-Effective: Affordable solution for high-quality signage and displays.",
          "Versatile Applications: Suitable for signs, displays, exhibits, and retail graphics.",
          "Easy to Customize: Can be cut, routed, and shaped to specific design requirements.",
        ],
        gallery: [
          "/imagesservices/WIDEFORMATPRINTS/PVCPRINTS/1.jpg",
          "/imagesservices/WIDEFORMATPRINTS/PVCPRINTS/2.jpg",
          "/imagesservices/WIDEFORMATPRINTS/PVCPRINTS/3.jpg",
          "/imagesservices/WIDEFORMATPRINTS/PVCPRINTS/4.jpg",
          "/imagesservices/WIDEFORMATPRINTS/PVCPRINTS/5.jpg",
          "/imagesservices/WIDEFORMATPRINTS/PVCPRINTS/6.jpg",
          "/imagesservices/WIDEFORMATPRINTS/PVCPRINTS/7.jpg",

        ],
      },
      {
        name: "WALL DECALS",
        image_url: "/imagesservices/WIDEFORMATPRINTS/WALLDECALS/1.jpg",
        description: "",
        benefits: [
          "Transform Spaces: Completely change the look of walls without paint or permanent changes.",
          "Easy Application: Professional installation with precision alignment and bubble-free results.",
          "Removable & Repositionable: Can be removed without damaging surfaces when needed.",
          "Custom Designs: Any artwork, logo, or pattern can be reproduced at any scale.",
          "Cost-Effective Branding: High-impact visual branding at a fraction of traditional methods.",
        ],
        gallery: [
          "/imagesservices/WIDEFORMATPRINTS/WALLDECALS/1.jpg",
          "/imagesservices/WIDEFORMATPRINTS/WALLDECALS/2.jpg",
          "/imagesservices/WIDEFORMATPRINTS/WALLDECALS/3.jpg",
          "/imagesservices/WIDEFORMATPRINTS/WALLDECALS/4.jpg",
          "/imagesservices/WIDEFORMATPRINTS/WALLDECALS/5.jpg",
          "/imagesservices/WIDEFORMATPRINTS/WALLDECALS/6.jpg",
          "/imagesservices/WIDEFORMATPRINTS/WALLDECALS/7.jpg",
        ],
      },
      {
        name: "VINYL",
        image_url: "/imagesservices/WIDEFORMATPRINTS/VINYL/1.jpg",
        description: "",
        benefits: [
          "Daylight Visibility: Transparent designs allow light in while displaying messages to outside viewers.",
          "Increased Privacy: Frosted or patterned decals provide privacy while maintaining natural light.",
          "Non-Obstructive Advertising: Promotes businesses without completely blocking window views.",
          "UV Resistant: Specialized materials prevent fading from sun exposure.",
          "Easy Installation & Removal: Professional application with clean removal options.",
        ],
        gallery: [
          "/imagesservices/WIDEFORMATPRINTS/VINYL/1.jpg",
          "/imagesservices/WIDEFORMATPRINTS/VINYL/2.jpg",
          "/imagesservices/WIDEFORMATPRINTS/VINYL/3.jpg",
          "/imagesservices/WIDEFORMATPRINTS/VINYL/4.jpg",
        
        ],
      },
       {
        name: "WINDOW DECALS",
        image_url: "/imagesservices/WIDEFORMATPRINTS/WINDOWDECALS/1.jpg",
        description: "",
        benefits: [
          "Daylight Visibility: Transparent designs allow light in while displaying messages to outside viewers.",
          "Increased Privacy: Frosted or patterned decals provide privacy while maintaining natural light.",
          "Non-Obstructive Advertising: Promotes businesses without completely blocking window views.",
          "UV Resistant: Specialized materials prevent fading from sun exposure.",
          "Easy Installation & Removal: Professional application with clean removal options.",
        ],
        gallery: [
          "/imagesservices/WIDEFORMATPRINTS/WINDOWDECALS/1.jpg",
          "/imagesservices/WIDEFORMATPRINTS/WINDOWDECALS/2.jpg",
          "/imagesservices/WIDEFORMATPRINTS/WINDOWDECALS/3.jpg",
          "/imagesservices/WIDEFORMATPRINTS/WINDOWDECALS/4.jpg",
          "/imagesservices/WIDEFORMATPRINTS/WINDOWDECALS/5.jpg",
          "/imagesservices/WIDEFORMATPRINTS/WINDOWDECALS/6.jpg",
          "/imagesservices/WIDEFORMATPRINTS/WINDOWDECALS/7.jpg",
          "/imagesservices/WIDEFORMATPRINTS/WINDOWDECALS/8.jpg",
          "/imagesservices/WIDEFORMATPRINTS/WINDOWDECALS/9.jpg",
          "/imagesservices/WIDEFORMATPRINTS/WINDOWDECALS/10.jpg",
          "/imagesservices/WIDEFORMATPRINTS/WINDOWDECALS/11.jpg",
          "/imagesservices/WIDEFORMATPRINTS/WINDOWDECALS/12.jpg",
          "/imagesservices/WIDEFORMATPRINTS/WINDOWDECALS/13.jpg",
          "/imagesservices/WIDEFORMATPRINTS/WINDOWDECALS/14.jpg",
          "/imagesservices/WIDEFORMATPRINTS/WINDOWDECALS/15.jpg",
          "/imagesservices/WIDEFORMATPRINTS/WINDOWDECALS/16.jpg",
          "/imagesservices/WIDEFORMATPRINTS/WINDOWDECALS/17.jpg",
          "/imagesservices/WIDEFORMATPRINTS/WINDOWDECALS/18.jpg",
          "/imagesservices/WIDEFORMATPRINTS/WINDOWDECALS/19.jpg",
          "/imagesservices/WIDEFORMATPRINTS/WINDOWDECALS/20.jpg",
          "/imagesservices/WIDEFORMATPRINTS/WINDOWDECALS/21.jpg",
          "/imagesservices/WIDEFORMATPRINTS/WINDOWDECALS/22.jpg",
          "/imagesservices/WIDEFORMATPRINTS/WINDOWDECALS/23.jpg",
          "/imagesservices/WIDEFORMATPRINTS/WINDOWDECALS/24.jpg",
          "/imagesservices/WIDEFORMATPRINTS/WINDOWDECALS/25.jpg",
          "/imagesservices/WIDEFORMATPRINTS/WINDOWDECALS/26.jpg",
        ],
      },
    ],
  },
];
